main/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('market.urls')),
]

market/urls.py
from django.urls import path

from market.views import (ApartmentDetailView, ApartmentListView, HomePageView,
                          HouseDetailView, HouseListView, SellHomeView)

app_name = 'market'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('sell/', SellHomeView.as_view(), name='sell_home'),
    path('house/', HouseListView.as_view(), name='house_list'),
    path('house/<uuid:pk>/', HouseDetailView.as_view(), name='house_detail'),
    path('apartment/', ApartmentListView.as_view(), name='apartment_list'),
    path('apartment/<uuid:pk>/', ApartmentDetailView.as_view(), name='apartment_detail'),
]

market/models.py
import uuid
from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse


class Property(models.Model):
    """
    Abstract Property model which won't be registered in the database.
    Meant as a place holder to store common attributes among all properties
    """
    RENT = 'RT'
    SALE = 'SL'

    OFFER_CHOICES = [
        (RENT, 'Rent'),
        (SALE, 'Sale'),
    ]

    square_footage = models.PositiveIntegerField(verbose_name='Area in sqft')
    num_bedrooms = models.PositiveSmallIntegerField('Number of bedrooms', default=3)
    num_bathrooms = models.PositiveSmallIntegerField('Number of bathrooms', default=2)
    offer = models.CharField(max_length=2, choices=OFFER_CHOICES, default=SALE)
    price = models.DecimalField(max_digits=12, decimal_places=0, validators=[MinValueValidator(Decimal('1'))])

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        ordering = ['-updated_on', ]


class House(Property):
    ATTACHED = 'AT'
    DETACHED = 'DT'
    NONE = 'NO'

    GARAGE_CHOICES = [
        (ATTACHED, 'Attached'),
        (DETACHED, 'Detached'),
        (NONE, 'None'),
    ]

    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    num_stories = models.PositiveSmallIntegerField('Number of stories')
    garage = models.CharField(max_length=2, choices=GARAGE_CHOICES, default=ATTACHED)
    yard_fenced = models.BooleanField('Is the yard fenced?', default=True)

    def __str__(self):
        return f'{self.square_footage}sqft-{self.num_stories}stories-${self.price}'

    def get_absolute_url(self):
        return reverse('market:house_detail', args=[str(self.id)])


class Apartment(Property):
    ENSUITE = 'EN'
    COIN = 'CO'
    OFFSITE = 'OF'

    LAUNDRY_CHOICES = [
        (ENSUITE, 'Ensuite'),
        (COIN, 'Coin'),
        (OFFSITE, 'Offsite'),
    ]

    id = models.UUIDField(primary_key=True, editable=False, default=uuid.uuid4)
    balcony = models.BooleanField('Has a balcony?', default=True)
    laundry = models.CharField(max_length=2, choices=LAUNDRY_CHOICES, default=ENSUITE)

    def __str__(self):
        return f'{self.square_footage}sqft-${self.price}'

    def get_absolute_url(self):
        return reverse('market:apartment_detail', args=[str(self.id)])

market/views.py
from django.views.generic import DetailView, ListView, TemplateView

from market.models import Apartment, House


class HomePageView(TemplateView):
    template_name = 'market/home.html'


class PropertyListView(ListView):
    model = None
    template_name = 'market/property_list.html'
    context_object_name = 'property_list'


class PropertyDetailView(DetailView):
    model = None
    template_name = 'market/property_detail.html'
    context_object_name = 'property'


class HouseListView(PropertyListView):
    model = House


class HouseDetailView(PropertyDetailView):
    model = House


class ApartmentListView(PropertyListView):
    model = Apartment


class ApartmentDetailView(PropertyDetailView):
    model = Apartment


class SellHomeView(TemplateView):
    template_name = 'market/sell_home.html'

market/templates/market/home.html
{% extends 'base.html' %}

{% block content %}

<div class="input-group flex-nowrap">
    <input type="text" class="form-control" placeholder="Find my home" aria-label="Find my home"
        aria-describedby="addon-wrapping">
    <button class="btn btn-outline-secondary" type="button" id="button-addon2">Search</button>
</div>

<p class="display-6 text-center">Whether you are buying, selling or renting we can help you move forward.</p>

<div class="row">
    <div class="col-sm-12 col-md-4">
        <div class="card mb-3 text-center">
            <div class="card-body">
                <h5 class="card-title">Buy a home</h5>
                <p class="card-text">Find your place with an immersive photo experience and the most listings, including
                    things you won't find anywhere else.</p>
                <a href="#" class="btn btn-outline-primary">Search homes</a>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-4">
        <div class="card mb-3 text-center">
            <div class="card-body">
                <h5 class="card-title">Sell a home</h5>
                <p class="card-text">Whether you get a cash offer through Casa Offers or choose to sell traditionally,
                    we can help you navigate a successful sale.</p>
                <a href="{% url 'market:sell_home' %}" class="btn btn-outline-primary">See your options</a>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-4">
        <div class="card mb-3 text-center">
            <div class="card-body">
                <h5 class="card-title">Rent a home</h5>
                <p class="card-text">We are creating a seamless online experience - from shopping on the largest rental
                    network, to applying, to paying rent.</p>
                <a href="#" class="btn btn-outline-primary">Find rentals</a>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

market/templates/market/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.79.0">
    <title>Pricing example · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/pricing/">

    

    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="pricing.css" rel="stylesheet">
  </head>
  <body>
    
<header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
  <p class="h5 my-0 me-md-auto fw-normal">Company name</p>
  <nav class="my-2 my-md-0 me-md-3">
    <a class="p-2 text-dark" href="#">Features</a>
    <a class="p-2 text-dark" href="#">Enterprise</a>
    <a class="p-2 text-dark" href="#">Support</a>
    <a class="p-2 text-dark" href="#">Pricing</a>
  </nav>
  <a class="btn btn-outline-primary" href="#">Sign up</a>
</header>

<main class="container">
  <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Pricing</h1>
    <p class="lead">Quickly build an effective pricing table for your potential customers with this Bootstrap example. It’s built with default Bootstrap components and utilities with little customization.</p>
  </div>

  <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
      <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 fw-normal">Free</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$0 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>10 users included</li>
          <li>2 GB of storage</li>
          <li>Email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="w-100 btn btn-lg btn-outline-primary">Sign up for free</button>
      </div>
    </div>
    </div>
    <div class="col">
      <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 fw-normal">Pro</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$15 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>20 users included</li>
          <li>10 GB of storage</li>
          <li>Priority email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="w-100 btn btn-lg btn-primary">Get started</button>
      </div>
    </div>
    </div>
    <div class="col">
      <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 fw-normal">Enterprise</h4>
      </div>
      <div class="card-body">
        <h1 class="card-title pricing-card-title">$29 <small class="text-muted">/ mo</small></h1>
        <ul class="list-unstyled mt-3 mb-4">
          <li>30 users included</li>
          <li>15 GB of storage</li>
          <li>Phone and email support</li>
          <li>Help center access</li>
        </ul>
        <button type="button" class="w-100 btn btn-lg btn-primary">Contact us</button>
      </div>
    </div>
    </div>
  </div>

  <footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <img class="mb-2" src="../assets/brand/bootstrap-logo.svg" alt="" width="24" height="19">
        <small class="d-block mb-3 text-muted">&copy; 2017-2020</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="#">Cool stuff</a></li>
          <li><a class="link-secondary" href="#">Random feature</a></li>
          <li><a class="link-secondary" href="#">Team feature</a></li>
          <li><a class="link-secondary" href="#">Stuff for developers</a></li>
          <li><a class="link-secondary" href="#">Another one</a></li>
          <li><a class="link-secondary" href="#">Last time</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="#">Resource</a></li>
          <li><a class="link-secondary" href="#">Resource name</a></li>
          <li><a class="link-secondary" href="#">Another resource</a></li>
          <li><a class="link-secondary" href="#">Final resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="link-secondary" href="#">Team</a></li>
          <li><a class="link-secondary" href="#">Locations</a></li>
          <li><a class="link-secondary" href="#">Privacy</a></li>
          <li><a class="link-secondary" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>
</main>


    
  </body>
</html>

market/templates/market/property_detail.html
{% extends 'base.html' %}

{% block content %}
<p class="display-4">Property detail</p>
{{ property }}
{% endblock content %}

market/templates/market/property_list.html
{% extends 'base.html' %}

{% block content %}

<div class="display-4">Properties List</div>

<ul>
    {% for property in property_list %}
    <li><a href="{{ property.get_absolute_url }}">{{ property }}</a></li>
    {% endfor %}
</ul>

{% endblock content %}

market/templates/market/search_results.html
{% extends 'base.html' %}

{% block title %}Search{% endblock title %}
{% block content %}
<h1>Search Results</h1>
{% endblock content %}

market/templates/market/sell_home.html
{% extends 'base.html' %}
{% block title %}Sell{% endblock title %}

{% block content %}

<div class="px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Sell with confidence</h1>
    <p class="lead">We are making it easier and safer to sell your home and move forward.</p>
</div>

<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
    <div class="col">
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 fw-normal">Sell Yourself</h4>
            </div>
            <div class="card-body">
                <p>Reach the largest audience of shoppers with a free listing.</p>
                <button type="button" class="w-100 btn btn-lg btn-outline-primary">Create a listing</button>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 fw-normal">Work with an agent</h4>
            </div>
            <div class="card-body">
                <p>Our premier Agents are among the best in the business. Learn to <a>pick the right one for you.</a>
                </p>
                <button type="button" class="w-100 btn btn-lg btn-primary">Get started</button>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h4 class="my-0 fw-normal">Enterprise</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title">$29 <small class="text-muted">/ mo</small></h1>
                <ul class="list-unstyled mt-3 mb-4">
                    <li>30 users included</li>
                    <li>15 GB of storage</li>
                    <li>Phone and email support</li>
                    <li>Help center access</li>
                </ul>
                <button type="button" class="w-100 btn btn-lg btn-primary">Contact us</button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>{% block title %}Casa{% endblock title %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'market:home' %}">CASA</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md">
                    <img class="mb-2" src="../assets/brand/bootstrap-logo.svg" alt="" width="24" height="19">
                    <small class="d-block mb-3 text-muted">&copy; 2017-2020</small>
                </div>
                <div class="col-6 col-md">
                    <h5>Features</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="link-secondary" href="#">Cool stuff</a></li>
                        <li><a class="link-secondary" href="#">Random feature</a></li>
                        <li><a class="link-secondary" href="#">Team feature</a></li>
                        <li><a class="link-secondary" href="#">Stuff for developers</a></li>
                        <li><a class="link-secondary" href="#">Another one</a></li>
                        <li><a class="link-secondary" href="#">Last time</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Resources</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="link-secondary" href="#">Resource</a></li>
                        <li><a class="link-secondary" href="#">Resource name</a></li>
                        <li><a class="link-secondary" href="#">Another resource</a></li>
                        <li><a class="link-secondary" href="#">Final resource</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>About</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="link-secondary" href="#">Team</a></li>
                        <li><a class="link-secondary" href="#">Locations</a></li>
                        <li><a class="link-secondary" href="#">Privacy</a></li>
                        <li><a class="link-secondary" href="#">Terms</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
</body>

</html>